apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-registry
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-once
