apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-once
  namespace: registry
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "10.0.11.10"
    path: "/mnt/Data"
  mountOptions:
    - nfsvers=4.1
