apiVersion: v1
data:
  REGISTRY_AUTH: 
  REGISTRY_AUTH_HTPASSWD_PATH: 
  REGISTRY_AUTH_HTPASSWD_REALM: 
  REGISTRY_HTTP_ADDR: 
  REGISTRY_HTTP_HOST: 
  REGISTRY_HTTP_SECRET: 
  REGISTRY_HTTP_TLS_CERTIFICATE: 
  REGISTRY_HTTP_TLS_KEY: 
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-secrets
  namespace: registry
